[package]
name = "crabble"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.3.0"
bevy_reflect = "0.11.3"
chumsky = { version = "1.0.0-alpha.6", features = ["label"] }
cranelift = "0.100.0"
cranelift-jit = "0.100"
cranelift-module = "0.100.0"
cranelift-native = "0.100.0"
